[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme", "hatch-requirements-txt", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "trilobot"
dynamic = ["version", "readme", "optional-dependencies"]
description = "Trilobot, a mid-level robot learning platform aimed at the Raspberry Pi SBC range"
license = {file = "LICENSE"}
requires-python = ">= 3.9"
authors = [
    { name = "Christopher Parrott", email = "chris@pimoroni.com" },
]
maintainers = [
    { name = "Christopher Parrott", email = "chris@pimoroni.com" },
    { name = "Philip Howard", email = "phil@pimoroni.com" },
]
keywords = [
    "Pi",
    "Raspberry",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Hardware",
]
dependencies = [
    "sn3218>=2.0.0",
    "evdev",
    "rpi-lgpio>=0.6 ; platform_machine == 'aarch64' or platform_machine == 'armv7l' or platform_machine == 'armv6l'"
]

[tool.hatch.metadata.hooks.requirements_txt.optional-dependencies]
example-depends = ["requirements-examples.txt"]

[project.urls]
GitHub = "https://www.github.com/pimoroni/trilobot-python"
Homepage = "https://www.pimoroni.com"

[dependency-groups]
dev = [
    "check-manifest",
    "ruff",
    "codespell",
    "pre-commit",
    "twine",
    "hatch",
    "hatch-fancy-pypi-readme",
    "hatch-requirements-txt",
    "uv-dynamic-versioning",
    "tox",
    "pdoc",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
fallback-version = "0.0.0"

[tool.hatch.build]
include = [
    "trilobot",
    "requirements-examples.txt"
]

[tool.hatch.build.targets.sdist]
include = [
    "*"
]
exclude = [
    ".*",
    "dist",
    "uv.lock"
]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [
  { path = "README.md" },
  { text = "\n" },
  { path = "CHANGELOG.md" }
]

[tool.ruff]
exclude = [
    '.tox',
    '.egg',
    '.git',
    '__pycache__',
    'build',
    'dist'
]
ignore = [
    'F403',
    'F405'
]

line-length = 200

[tool.ruff.lint]
extend-select = ["I"]

[tool.codespell]
skip = """
./.tox,\
./.egg,\
./.git,\
./__pycache__,\
./build,\
./dist.\
"""

[tool.check-manifest]
ignore = [
    'boilerplate.md',
    'install.sh',
    'uninstall.sh',
    'Makefile',
    'tox.ini',
    'tests/*',
    'examples/*',
    '.coveragerc',
    '.editorconfig',
    '.pre-commit-config.yaml',
]

[tool.pimoroni]
apt_packages = []
configtxt = []
commands = [
    "sudo raspi-config nonint do_i2c 0"
]
